// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3MjhbOdIp2AGXNkkOYuXxYeOBqKQNjPk',
    appId: '1:1087573506516:web:e1287d0f29714d05ba3e41',
    messagingSenderId: '1087573506516',
    projectId: 'expence-tracker-39050',
    authDomain: 'expence-tracker-39050.firebaseapp.com',
    storageBucket: 'expence-tracker-39050.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqm_-3GNet0HA1e71LpKSbgfKIx_4mbSA',
    appId: '1:1087573506516:android:335598e171c041f9ba3e41',
    messagingSenderId: '1087573506516',
    projectId: 'expence-tracker-39050',
    storageBucket: 'expence-tracker-39050.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZAsfmpwUyBQqck3XM_4S261Qc9w9oWwE',
    appId: '1:1087573506516:ios:bb993719b00623b4ba3e41',
    messagingSenderId: '1087573506516',
    projectId: 'expence-tracker-39050',
    storageBucket: 'expence-tracker-39050.appspot.com',
    iosBundleId: 'com.example.getIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZAsfmpwUyBQqck3XM_4S261Qc9w9oWwE',
    appId: '1:1087573506516:ios:bb993719b00623b4ba3e41',
    messagingSenderId: '1087573506516',
    projectId: 'expence-tracker-39050',
    storageBucket: 'expence-tracker-39050.appspot.com',
    iosBundleId: 'com.example.getIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3MjhbOdIp2AGXNkkOYuXxYeOBqKQNjPk',
    appId: '1:1087573506516:web:1442dd518f04ff23ba3e41',
    messagingSenderId: '1087573506516',
    projectId: 'expence-tracker-39050',
    authDomain: 'expence-tracker-39050.firebaseapp.com',
    storageBucket: 'expence-tracker-39050.appspot.com',
  );
}
